### ISSUE TITLE
Detail information in training

### ISSUE THREAD

**Issue by Leong1230** [wulalago/AgentSPL#3]
Hi, thank you for sharing the work! I have a question concerning training the network for different SPs: 
From mt point of view, the trained RL agent may only capture relationship between images and spatial postions for the specific organ and it is hard to generalize. Did you explore how the RL agent training on organ A would perform on organ B (the generalization problem), or I missed the information in the work? 
Should I train the network from scratch ervey time I want to use it to localize anothor SP, or even SPs in images of other organs (but same modality)？

I am  interested in this topic~
Thank you!

**Comment by wulalago** [comment]
> Hi, thank you for sharing the work! I have a question concerning training the network for different SPs: From mt point of view, the trained RL agent may only capture relationship between images and spatial postions for the specific organ and it is hard to generalize. Did you explore how the RL agent training on organ A would perform on organ B (the generalization problem), or I missed the information in the work? Should I train the network from scratch ervey time I want to use it to localize anothor SP, or even SPs in images of other organs (but same modality)？
> 
> I am interested in this topic~ Thank you!

**How is the RL agent's performance on organ B when it was trained on organ A?** 
We didn't explore this since the SPs on different organs have a large variation in the content.
**Should I train the network from scratch ervey time I want to use it to localize anothor SP?**
Yes, it does. Our proposed method is designed for a single SP in one organ. Any other SP localization problem should be trained from scratch.
